pipeline { 
agent any 
    stages { 
        stage ('Build') { 
            steps{
                echo "Build"
                sh 'git checkout Webchat_with_sample'
                sh 'git pull'
                sh 'cd Webchat_with_sample'
                sh './gradlew clean build'
            }
        }
        stage ('Test') { 
            steps{
                echo "Test"
            }
        }
        stage ('QA') { 
            steps{
                echo "QA"
            }
        }
        stage ('Deploy') { 
            steps{
                echo "Deploy"
            }
        }
        stage ('Monitor') { 
            steps{
                echo "Monitor"
            }
        }
 
    }           
 }