pipeline { 
agent any 
    stages { 
        stage ('Build') { 
            steps{
                echo "Build"
                'git checkout Webchat_with_sample'
                'git pull'
                'cd Webchat_with_sample'
                './gradlew clean build'
            }
        }
        stage ('Test') { 
            steps{
                echo "Test"
            }
        }
        stage ('QA') { 
            steps{
                echo "QA"
            }
        }
        stage ('Deploy') { 
            steps{
                echo "Deploy"
            }
        }
        stage ('Monitor') { 
            steps{
                echo "Monitor"
            }
        }
 
    }           
 }