spring:
  datasource:
    url: jdbc:h2:mem:tempdb
    driverClassName: org.h2.Driver
    username: sa
    password: pass
    database-platform: org.hibernate.dialet.H2Dialet
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: dd58f83096cdc761e1d9
            client-secret: 095778fe44e632a595e12bc15a5c36f8d46dedd6

logging:
  level:
    root: INFO

